### ISSUE TITLE
Error: Use `path` instead of `fp` when using `load` function

### ISSUE THREAD

**Issue by mirusu400** [ita9naiwa/pyyjson#1]
https://docs.python.org/ko/3/library/json.html#json.load

On a python json documentation, `json.load` takes `fp` as an argument and deserializes it as a Python object.

https://github.com/ita9naiwa/pyyjson/blob/f9c97187894d8514a367935a06b8659f4cafb90b/pyyjson/wrapper.py#L44-L52

However, pyyjson takes the file path as a argument when 'pyyjson.load', so the following error occurs when fp is delivered.

```
Traceback (most recent call last):
  File "C:\Users\OWNER\Documents\_github\pyyjson\test.py", line 23, in <module>
    benchmark()
  File "C:\Users\OWNER\Documents\_github\pyyjson\test.py", line 14, in benchmark
    data2 = pyyjson.load(open("merge.json", "r", encoding="utf-8"))
  File "C:\Users\OWNER\Documents\_github\pyyjson\pyyjson\wrapper.py", line 46, in load
    if os.path.exists(path):
  File "C:\Users\OWNER\AppData\Local\Programs\Python\Python39\lib\genericpath.py", line 19, in exists
    os.stat(path)
TypeError: stat: path should be string, bytes, os.PathLike or integer, not TextIOWrapper
```

If pyyjson is to be compatible with the functionality of the json standard library, I think it needs to be addressed.

**Comment by ita9naiwa** [comment]
Now 'load', and 'dump' accept filename (given string type) as file path.
